name: nork
description: "nork project"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  synchronized: ^3.1.0+1
  provider: ^6.1.2
  dart_jsonwebtoken: ^2.14.0
  flutter_phoenix: ^1.1.1
  loading_animation_widget: ^1.2.1
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
